const table = [
  // Common (GTA-themed everyday trash)
  { rarity: "Common", name: "Crumpled Joint", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "Half-Eaten Burger Shot", min: 1, max: 12, weight: 40 },
  { rarity: "Common", name: "Dead Rat", min: 2, max: 15, weight: 40 },
  { rarity: "Common", name: "Empty Pisswasser Can", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "Moldy Bread Slice", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Burnt Cigarette Butt", min: 1, max: 6, weight: 40 },
  { rarity: "Common", name: "Burger Shot Napkin", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Pisswasser Bottle Cap", min: 1, max: 9, weight: 40 },
  { rarity: "Common", name: "Meteorite Bar Wrapper", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "E-Cola Can (Empty)", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "Sprunk Bottle (Empty)", min: 1, max: 12, weight: 40 },
  { rarity: "Common", name: "Bleeter Pamphlet", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "Los Santos Transit Ticket Stub", min: 2, max: 14, weight: 40 },
  { rarity: "Common", name: "Del Perro Souvenir Bracelet (Broken)", min: 2, max: 14, weight: 40 },
  { rarity: "Common", name: "Mount Chiliad Hiking Map (Torn)", min: 2, max: 15, weight: 40 },
  { rarity: "Common", name: "Vinewood Star Flyer", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "Lucky Plucker Fry Box", min: 1, max: 12, weight: 40 },
  { rarity: "Common", name: "24/7 Receipt", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "LTD Gas Receipt", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "iFruit Charger Cable (Frayed)", min: 2, max: 15, weight: 40 },
  { rarity: "Common", name: "Lifeinvader Sticker (Peeling)", min: 1, max: 9, weight: 40 },
  { rarity: "Common", name: "Cluckin' Bell Nugget Box", min: 1, max: 12, weight: 40 },
  { rarity: "Common", name: "Maze Bank Promo Pen (Dry)", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Ron Oil Rag", min: 2, max: 15, weight: 40 },
  { rarity: "Common", name: "Redwood Cigarette Pack (Empty)", min: 2, max: 14, weight: 40 },
  { rarity: "Common", name: "Pisswasser Coaster (Stained)", min: 1, max: 9, weight: 40 },
  { rarity: "Common", name: "Taco Bomb Napkin", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Ponsonbys Tag", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Suburban Tag", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Binco Price Tag", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Ammu-Nation Catalog (Crumpled)", min: 2, max: 15, weight: 40 },
  { rarity: "Common", name: "Blaine County Lottery Ticket (Expired)", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "Los Santos Parking Ticket", min: 2, max: 15, weight: 40 },
  { rarity: "Common", name: "Weazel News Flyer", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "Richards Majestic Ticket Stub", min: 1, max: 12, weight: 40 },
  { rarity: "Common", name: "Vinewood Boulevard Brochure", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "Bus Pass (Expired)", min: 2, max: 15, weight: 40 },
  { rarity: "Common", name: "Sandy Shores Postcard", min: 1, max: 9, weight: 40 },
  { rarity: "Common", name: "Grapeseed Farm Coupon", min: 1, max: 9, weight: 40 },
  { rarity: "Common", name: "Pacific Standard ATM Receipt", min: 1, max: 12, weight: 40 },
  { rarity: "Common", name: "Epsilon Pamphlet", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "Tire Valve Cap (Stolen)", min: 2, max: 14, weight: 40 },
  { rarity: "Common", name: "Rusty Nail", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Plastic Spoon", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Bottle Shard", min: 2, max: 15, weight: 40 },
  { rarity: "Common", name: "Broken Sunglasses", min: 2, max: 15, weight: 40 },
  { rarity: "Common", name: "Bent Spoon", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Torn Hoodie String", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Used Bandage (Gross)", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Chewed Gum", min: 1, max: 6, weight: 40 },
  { rarity: "Common", name: "Plastic Baggie (Empty)", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Coffee Cup Lid", min: 1, max: 8, weight: 40 },
  { rarity: "Common", name: "Train Ticket (Old)", min: 2, max: 15, weight: 40 },
  { rarity: "Common", name: "Movie Flyer (Old)", min: 1, max: 10, weight: 40 },
  { rarity: "Common", name: "Arcade Token (Worn)", min: 2, max: 14, weight: 40 },
  { rarity: "Common", name: "Single Work Glove (Used)", min: 2, max: 15, weight: 40 },

  // Uncommon (mid-value street finds)
  { rarity: "Uncommon", name: "Half-Smoked Joint", min: 15, max: 35, weight: 20 },
  { rarity: "Uncommon", name: "Bag of Weed Crumbs", min: 20, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Damaged Pistol Slide", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Intact Burner Phone", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Loose Cash Roll", min: 15, max: 50, weight: 20 },
  { rarity: "Uncommon", name: "Redwood Half Pack", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Skateboard Wheel", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Scrap Copper Wire", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Old Phone Battery", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Drone Propeller (Broken)", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Motor Oil Can (Half)", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Used Spark Plug", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Loose 9mm Rounds", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Cheap Watch (Broken)", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Transit Punch Card", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Expired ID Card", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Worn Hoodie", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Knife Sheath (Empty)", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Scuffed Sunglasses", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "VHS Tape: Vinewood", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Transit Day Pass (Stolen)", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Del Perro Poker Chip", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "LS Car Meet Racing Flyer", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Bent Tire Iron", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "E-Cola Crate Label", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Lifeinvader USB (Fake)", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "iFruit Earbud (Single)", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Disposable Camera", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Small Cash Clip", min: 20, max: 50, weight: 20 },
  { rarity: "Uncommon", name: "Gas Mask Filter (Used)", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Bat Grip Tape", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Park Ranger Patch", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Replica Blaine County Badge", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Small Bleach Bottle", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Car Jack Handle", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Toolkit Screwdriver", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Spray Paint Can (Half)", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Firework Stick", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Motorcycle Gloves (Pair)", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Drift Tire Chunk", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "SNS Pistol Spring (Damaged)", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Hammer Head (Loose)", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Door Lock Cylinder", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Car Key Blank", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Mini Bolt Cutters", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Walkie-Talkie (Dead)", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "USB Drive (64MB)", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "GPS Tracker (Dead)", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Police Scanner (Toy)", min: 20, max: 45, weight: 20 },
  { rarity: "Uncommon", name: "Cheap Mask", min: 15, max: 35, weight: 20 },
  { rarity: "Uncommon", name: "Light Chains", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Metal Pipe Section", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Spark Plug Wires", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Headlight Bulb", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Fire Extinguisher Pin", min: 18, max: 40, weight: 20 },
  { rarity: "Uncommon", name: "Tattoo Ink Vial (Used)", min: 18, max: 40, weight: 20 },

  // Rare (high-end loot & parts)
  { rarity: "Rare", name: "Full Weed Baggy - Vinewood OG", min: 80, max: 150, weight: 4 },
  { rarity: "Rare", name: "Solid Meth Chunk", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Clean Pistol Barrel", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "High-End Car Key Fob", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Exotic Car ECU", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Extended Mag (Rifle)", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "Tactical Scope Housing", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Suppressed Barrel Section", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "NOS Canister (Small)", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Kevlar Plate (Used)", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Night Vision Monocular", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Drone Battery (High-End)", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Casino VIP Card", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "Yacht Access Card", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Gold Chain (Thin)", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Diamond Earring (Single)", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Rifle Bolt (Polished)", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "Shotgun Choke (Clean)", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "Car Meet Trophy Plate", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Prototype iFruit Phone", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Lifeinvader Dev USB", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Counterfeit Plates Set", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Smuggled Cigars Box", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Military Radio (Surplus)", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Pelican Case (Tools)", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "Tactical Flashlight (HL)", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "Kevlar Weave Roll", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Data Tape (Secure)", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Bank Manager Lanyard", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "High-Value Chip Rack", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Nightclub VIP Band", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "Limited Artwork Print", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Signed Epsilon Tract", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Rare Vinyl - WCTR", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "Movie Prop - Alien Egg", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Collectible Figurine (Mint)", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Prototype Micro SMG Grip", min: 100, max: 180, weight: 4 },
  { rarity: "Rare", name: "Silencer Kit (Incomplete)", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: ".50 Cal Dummy Round", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "Rifle Upper (Clean)", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Exotic Car Key (Tracked)", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "High-End Drone Frame", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Racing ECU Tune", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Gold Bar Shard", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Jewelry Store Key", min: 90, max: 160, weight: 4 },
  { rarity: "Rare", name: "Thermal Scope Housing", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "Drone Frame (Carbon)", min: 120, max: 200, weight: 4 },
  { rarity: "Rare", name: "High-Lumen Headlamp", min: 90, max: 160, weight: 4 },

  // Ultra-Rare (jackpot finds)
  { rarity: "Ultra-Rare", name: "Vac-Sealed Brick (??? Powder)", min: 300, max: 600, weight: 1 },
  { rarity: "Ultra-Rare", name: "Legendary Strain - San Andreas Supernova", min: 350, max: 800, weight: 1 },
  { rarity: "Ultra-Rare", name: "Mythic Meth Crystal", min: 400, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Briefcase of Marked Bills", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Duffel of Unmarked Cash", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Gold Bars Stack", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Diamond Necklace", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Pacific Standard Vault Blueprints", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Yacht Safe Key", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Casino Cash Cage Master Key", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "FIB Access Badge", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Offshore Account Ledger", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Illegal Weapon Cache Codebook", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Hacked Lifeinvader Admin Token", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Prototype Railgun Coil", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Minigun Barrel Cluster", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Rare Supercar ECU", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Art Heist Bundle", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Epsilon Gold Idol", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Exotic Animal Pelt", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Collector's Diamond Watch", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "UFO Component (Classified)", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Stash House Master Key", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Yacht Master Access Card", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Casino VIP Vault Pass", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Prototype LMG Upper", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Black Card (Unlimited)", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Gold Ingot Bundle", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "High-Roller Diamond Chip", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Museum Artifact (Stolen)", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Military Optics Array", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Encrypted FIB Drive", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Prototype Minigun Gear", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "VIP Nightclub Vault Key", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Gold Bracelet (Heavy)", min: 500, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Diamond Ring (Large)", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Prototype Railgun Housing", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "VIP Yacht Safe Code", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Casino Cage Ledger", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Collector's Gem Set", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Prototype Thermal Scope", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Stolen Gold Statue", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Diamond-Encrusted Watch", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Epsilon Relic (Blessed)", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Prototype Supercar ECU", min: 600, max: 1000, weight: 1 },
  { rarity: "Ultra-Rare", name: "Ultra-Rare Casino Chip", min: 600, max: 1000, weight: 1 }
];

const totalWeight = table.reduce((acc, item) => acc + item.weight, 0);

const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;

export const pickLoot = () => {
  const roll = Math.random() * totalWeight;
  let cumulative = 0;
  const selected = table.find(item => {
    cumulative += item.weight;
    return roll <= cumulative;
  }) ?? table[table.length - 1];
  const value = randomInt(selected.min, selected.max);
  return { ...selected, value };
};

export const levelFromXp = (xp, step = 1000) => Math.max(1, Math.floor(xp / step) + 1);

export { table as lootTable };
